# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b33f64b7029f0d44c7d4d252f454836587c35bc2612dcfab51244b76aa30957e335de7f46c7dd394947aa5e57428686a2903db6ba2b24cb2cb62b2053425c5c

test:
  secret_key_base: e84ed94f0554a902191c92e7aa45188565cb333425265c7eaec2c24d8f7cad981249bc8543e3af62bd1d15c672a27e4fea1fc95906aa4e561bbb09da38973818

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
